services:
  coordinator:
    build: .
    container_name: coordinator
    command: python -u services/coordinator.py
    volumes:
      - ./services:/app/services
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock

  checkpoint_manager:
    build: .
    container_name: checkpoint_manager
    command: python -u services/checkpoint_manager.py
    volumes:
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock

  worker1_primary:
    build: .
    container_name: worker1_primary
    labels:
      worker.id: "1"
      worker.role: "primary"
    command: python -u services/worker.py --role primary --id 1
    volumes:
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs

  worker1_redundant:
    build: .
    container_name: worker1_redundant
    labels:
      worker.id: "1"
      worker.role: "redundant"
    command: python -u services/worker.py --role redundant --id 1
    volumes:
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs
