services:
  coordinator:
    build: .
    container_name: coordinator
    command: python -u services/coordinator.py
    volumes:
      - ./services:/app/services
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs

  checkpoint_manager:
    build: .
    container_name: checkpoint_manager
    command: python -u services/checkpoint_manager.py
    volumes:
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs

  worker1:
    build: .
    container_name: worker1
    command: python -u services/worker.py --role primary --id 1
    volumes:
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs

  worker2:
    build: .
    container_name: worker2
    command: python -u services/worker.py --role redundant --id 1
    volumes:
      - ./shared_storage:/app/shared_storage
      - ./logs:/app/logs

  simulator:
    build: .
    container_name: simulator
    command: python -u services/simulator.py
    volumes:
      - ./logs:/app/logs

